# test_simple.yaml
initialConditions:
  file_path: "c:/Fac/M2_osae/census_project/MonteCarloMaker_Moni3/MonteCarlo/run_20260101_205721/initial_conditions_iter_001.txt"
  frame: ICRF
  format: [ISOT, KM, KM/S]
  center: [predefined, [Sun]]

ephemInput:
  spice_kernels: "C:/Fac/M2_osae/projet_census/docks-installer-master/docks-installer-master/DOCKS/kernel/"
  text_files: [ISOT, KM, KM/S]

perturbations:
  central_body: Sun
  predefined_bodies: ['Sun', 'Earth', 'Moon']  # le Soleil comme perturbation
  new_bodies_added: false
  complex_grav_model_activated: false
  non_grav_perturbations: []
  propulsion_burns_file: ""

new_grav_bodies:
  body1: {}

complex_grav_bodies:
  body1: {}

probeFeatures:
  mass: 10
  srp_area: 0.5
  srp_coefficient: 1.2

numericalMethod:
  method: rk4
  tolerance: 0
  safety_factor: 0

timeSettings:
  method: Duration
  propagation_time: [300, 00:00:00.000]  
  time_step_unit: seconds
  time_step: [60., 0., 0.]

output:
  directory: "C:/Fac/M2_osae/census_project/MonteCarloMaker_Moni3/MonteCarlo/run_20260101_205721"
  file_name: traj1.txt
  frame: ICRF
  format: [MJD_2COL, KM, KM/S, KM/S^2]
  step_divider: 10
  center: [predefined, [Sun]]